declare const parseVoxChunk: (id: string, contentData: Array<number>) => {
    nodeId: number;
    nodeAttributes: {
        _name: string;
        _hidden?: 0 | 1 | undefined;
    };
    child: number;
    reserved: number;
    layer: number;
    numFrames: number;
    frames: {
        _t: string;
    }[];
} | {
    nodeId: number;
    nodeAttributes: {
        _name: string;
        _hidden?: 0 | 1 | undefined;
    };
    child: number;
    children: number[];
} | {
    nodeId: number;
    nodeAttributes: any;
    numModels: number;
    models: any[];
} | {
    numColorNames: number;
    colorNames: string[];
} | {
    numModels: any;
    x?: undefined;
    y?: undefined;
    z?: undefined;
    numVoxels?: undefined;
    values?: undefined;
    materialId?: undefined;
    materialProperties?: undefined;
    layerId?: undefined;
    layerAttributes?: undefined;
    reservedId?: undefined;
    renderAttributes?: undefined;
    cameraId?: undefined;
    cameraAttributes?: undefined;
    indexAssociations?: undefined;
} | {
    x: any;
    y: any;
    z: any;
    numModels?: undefined;
    numVoxels?: undefined;
    values?: undefined;
    materialId?: undefined;
    materialProperties?: undefined;
    layerId?: undefined;
    layerAttributes?: undefined;
    reservedId?: undefined;
    renderAttributes?: undefined;
    cameraId?: undefined;
    cameraAttributes?: undefined;
    indexAssociations?: undefined;
} | {
    numVoxels: any;
    values: any;
    numModels?: undefined;
    x?: undefined;
    y?: undefined;
    z?: undefined;
    materialId?: undefined;
    materialProperties?: undefined;
    layerId?: undefined;
    layerAttributes?: undefined;
    reservedId?: undefined;
    renderAttributes?: undefined;
    cameraId?: undefined;
    cameraAttributes?: undefined;
    indexAssociations?: undefined;
} | {
    values: any;
    numModels?: undefined;
    x?: undefined;
    y?: undefined;
    z?: undefined;
    numVoxels?: undefined;
    materialId?: undefined;
    materialProperties?: undefined;
    layerId?: undefined;
    layerAttributes?: undefined;
    reservedId?: undefined;
    renderAttributes?: undefined;
    cameraId?: undefined;
    cameraAttributes?: undefined;
    indexAssociations?: undefined;
} | {
    materialId: any;
    materialProperties: any;
    numModels?: undefined;
    x?: undefined;
    y?: undefined;
    z?: undefined;
    numVoxels?: undefined;
    values?: undefined;
    layerId?: undefined;
    layerAttributes?: undefined;
    reservedId?: undefined;
    renderAttributes?: undefined;
    cameraId?: undefined;
    cameraAttributes?: undefined;
    indexAssociations?: undefined;
} | {
    layerId: any;
    layerAttributes: any;
    reservedId: any;
    numModels?: undefined;
    x?: undefined;
    y?: undefined;
    z?: undefined;
    numVoxels?: undefined;
    values?: undefined;
    materialId?: undefined;
    materialProperties?: undefined;
    renderAttributes?: undefined;
    cameraId?: undefined;
    cameraAttributes?: undefined;
    indexAssociations?: undefined;
} | {
    renderAttributes: any;
    numModels?: undefined;
    x?: undefined;
    y?: undefined;
    z?: undefined;
    numVoxels?: undefined;
    values?: undefined;
    materialId?: undefined;
    materialProperties?: undefined;
    layerId?: undefined;
    layerAttributes?: undefined;
    reservedId?: undefined;
    cameraId?: undefined;
    cameraAttributes?: undefined;
    indexAssociations?: undefined;
} | {
    cameraId: any;
    cameraAttributes: any;
    numModels?: undefined;
    x?: undefined;
    y?: undefined;
    z?: undefined;
    numVoxels?: undefined;
    values?: undefined;
    materialId?: undefined;
    materialProperties?: undefined;
    layerId?: undefined;
    layerAttributes?: undefined;
    reservedId?: undefined;
    renderAttributes?: undefined;
    indexAssociations?: undefined;
} | {
    indexAssociations: number[];
    numModels?: undefined;
    x?: undefined;
    y?: undefined;
    z?: undefined;
    numVoxels?: undefined;
    values?: undefined;
    materialId?: undefined;
    materialProperties?: undefined;
    layerId?: undefined;
    layerAttributes?: undefined;
    reservedId?: undefined;
    renderAttributes?: undefined;
    cameraId?: undefined;
    cameraAttributes?: undefined;
} | {
    numModels?: undefined;
    x?: undefined;
    y?: undefined;
    z?: undefined;
    numVoxels?: undefined;
    values?: undefined;
    materialId?: undefined;
    materialProperties?: undefined;
    layerId?: undefined;
    layerAttributes?: undefined;
    reservedId?: undefined;
    renderAttributes?: undefined;
    cameraId?: undefined;
    cameraAttributes?: undefined;
    indexAssociations?: undefined;
};
export = parseVoxChunk;
